### ISSUE TITLE
Problem Using Dawn with Ubuntu

### ISSUE THREAD

**Issue by DaGeRe** [DawnScience/dawn-ui#35]
Hi,

I am currently getting started with Dawn, and am stuck at the beginning: while according to http://www.dawnsci.org/tools/data-handling the Image ref-testscale_1_001.img should print some blue and green circles, nothing is printed and the view with Meta Data, which one can see, does not appear (and can not be opened via Show View).

Is this the right place to ask, or is one of the mailing lists better?

The following output is given:

> Starting BoofCV image filter service.
> Starting BoofCV image transform service.
> Starting BoofCV image Stitching service.
> Starting conversion service.
> Starting expression service.
> Starting JGoogleAnalytics Event tracker service.
> Started macro service
> Starting persistence service
> 18:48:06.169 DEBUG Set PersistenceServiceImpl in PersistenceServiceHolder 
> Starting analysis class loader service
> 18:48:06.194 DEBUG Set ClassLoaderService in ClassLoaderServiceHolder 
> Starting image service
> Starting PlotImageService
> Starting NeXus File Factory
> Creating BeanService
> Starting device service
> Starting generator service
> Started IJsonMarshaller
> Started ActivemqConnectorService
> Started IEventService
> Starting loader service
> Starting remote dataset service.
> Starting plotting system services loader
> Starting dataset maths service
> Starting plotting service
> Starting operation service
> Starting data reduction service for NCD
> 18:48:09.650 ERROR Could not create directory /dls/tmp/reichelt 
> 18:48:09.652 ERROR Could not create directory /dls/tmp/reichelt 
> 18:48:12.721 DEBUG Plotting system for 'ref-testscale_1_001.img' registered. 
> 18:48:13.232 DEBUG Starting org.embl.cca.dviewer 
> 18:48:13.233 DEBUG Started org.embl.cca.dviewer 
> 18:48:13.467 INFO  Registry not initialised. Queuing PlottingSystem:ref-testscale_1_001.img 
> 18:48:13.668 INFO  PlotServer instance not set - using local created PlotServer instead 
> 18:48:13.672 INFO  Registry not initialised. Queuing RMIPlotServer 
> 18:48:13.758 INFO  Starting Analysis RPC Server on port 43120 
> 18:48:13.758 INFO  Adding SDAPlotter 
> 18:48:13.762 INFO  Plot view uuid: 59423093-a975-4218-b465-0eb71dc9e398 
> 18:48:13.873 WARN  Ignoring problem with metadata in /home/reichelt/workspace/data/examples/ref-testscale_1_001.img 
> 18:48:14.289 WARN  Ignoring problem with metadata in /home/reichelt/workspace/data/examples/ref-testscale_1_001.img 
> 18:48:14.631 INFO  Registry not initialised. Queuing RMIPlotWindowManager 
> 18:48:14.631 INFO  Adding PlotWindowManager 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> 18:48:20.175 DEBUG Set UserInputService in org.dawb.passerelle.common.UserInputServiceHolder 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> 18:48:21.370 DEBUG Plotting system for 'ref-testscale_1_002.img' registered. 
> 18:48:21.427 INFO  Registry not initialised. Queuing PlottingSystem:ref-testscale_1_002.img 
> 18:48:21.429 WARN  Ignoring problem with metadata in /home/reichelt/workspace/data/examples/ref-testscale_1_002.img 
> 18:48:21.509 INFO  Plot view uuid: d03d9cc1-a117-40e2-bb5a-fbf1a7f8d992 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> 18:48:21.921 DEBUG Plotting system for 'ref-testscale_1_001.img' removed. 
> *** BUG ***
> In pixman_region32_init_rect: Invalid rectangle passed
> Set a breakpoint on '_pixman_log_error' to debug
> 
> 18:48:23.594 DEBUG Plotting system for 'ref-testscale_1_002.img' removed. 
> 18:48:24.105 DEBUG Running workbench not workflow, starting workbench service. 
> 18:48:24.128 DEBUG Used free port at 21701 
> 18:48:24.133 DEBUG Workbench URI: /jndi/rmi://reichelt-ThinkPad-T440s:21701/workbench 
> 18:48:24.634 DEBUG Workbench service started on service:jmx:rmi:///jndi/rmi://reichelt-ThinkPad-T440s:21701/workbench 
> 18:48:24.784 DEBUG Plotting system for 'ref-testscale_1_001.img' registered. 
> 18:48:24.898 INFO  Registry not initialised. Queuing PlottingSystem:ref-testscale_1_001.img 
> 18:48:24.954 INFO  Plot view uuid: dc61e90e-599e-45b0-9e1a-9cef88f252b1 
> 18:48:24.971 DEBUG There is a guiBean update: {ROI=null, ROIClearAll=true, PlotID=59423093-a975-4218-b465-0eb71dc9e398} 
> 18:48:25.737 DEBUG Started org.embl.cca.dviewer 
> 18:48:25.811 INFO  Registry not initialised. Queuing RMIDatasetManager 
> 18:48:25.812 INFO  Adding DatasetManager 
> 18:48:25.821 INFO  Local RMI server port has not been specified - looking for a free port... 
> 18:48:25.825 DEBUG Local RMI server port is now 36618 
> 18:48:25.837 INFO  Creating RMI Server on port 36618 
> 18:48:25.845 INFO  Adding RMI service RMIPlotServer 
> 18:48:25.864 INFO  Adding RMI service RMIPlotWindowManager 
> 18:48:25.885 INFO  Adding RMI service PlottingSystem:ref-testscale_1_001.img 
> 18:48:25.933 INFO  Adding RMI service RMIDatasetManager 
> 18:48:26.262 DEBUG Initialising the Jython interpreter setup 
> 18:48:26.264 DEBUG Plugins directory is /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins 
> 18:48:26.265 DEBUG Script path = /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.python.pydev_3.6.0.201406232321/pysrc/interpreterInfo.py 
> 18:48:26.290 DEBUG Using java: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/jre/bin/java 
> 18:48:26.291 INFO  Jython bundle found at: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.jython_2.5.3.v20151222-1720/jython2.5 
> 18:48:26.291 DEBUG executable path = /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.jython_2.5.3.v20151222-1720/jython2.5/jython.jar 
> 18:48:28.543 DEBUG Output String is <xml>
> <version>2.5</version>
> <executable>None</executable>
> <lib path="ins">/home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.jython_2.5.3.v20151222-1720/jython2.5/Lib/site-packages/distribute-0.6.28-py2.5.egg</lib>
> <lib path="ins">/home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.jython_2.5.3.v20151222-1720/jython2.5/Lib/site-packages/pip-1.1-py2.5.egg</lib>
> <lib path="ins">/home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.jython_2.5.3.v20151222-1720/jython2.5/Lib</lib>
> <lib path="out">__classpath__</lib>
> <lib path="out">__pyclasspath__</lib>
> <lib path="ins">/home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.jython_2.5.3.v20151222-1720/jython2.5/Lib/site-packages</lib>
> <lib path="ins">/home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.jython_2.5.3.v20151222-1720/jython2.5/Lib/site-packages/setuptools-0.6c11-py2.5.egg-info</lib>
> <forced_lib>struct</forced_lib>
> <forced_lib>jarray</forced_lib>
> <forced_lib>_marshal</forced_lib>
> <forced_lib>binascii</forced_lib>
> <forced_lib>ucnhash</forced_lib>
> <forced_lib>_sre</forced_lib>
> <forced_lib>sys</forced_lib>
> <forced_lib>imp</forced_lib>
> <forced_lib>cmath</forced_lib>
> <forced_lib>itertools</forced_lib>
> <forced_lib>operator</forced_lib>
> <forced_lib>jffi</forced_lib>
> <forced_lib>_py_compile</forced_lib>
> <forced_lib>array</forced_lib>
> <forced_lib>zipimport</forced_lib>
> <forced_lib>_codecs</forced_lib>
> <forced_lib>_hashlib</forced_lib>
> <forced_lib>gc</forced_lib>
> <forced_lib>posix</forced_lib>
> <forced_lib>synchronize</forced_lib>
> <forced_lib>cPickle</forced_lib>
> <forced_lib>_random</forced_lib>
> <forced_lib>errno</forced_lib>
> <forced_lib>__builtin__</forced_lib>
> <forced_lib>thread</forced_lib>
> <forced_lib>_weakref</forced_lib>
> <forced_lib>_csv</forced_lib>
> <forced_lib>exceptions</forced_lib>
> <forced_lib>_systemrestart</forced_lib>
> <forced_lib>_ast</forced_lib>
> <forced_lib>cStringIO</forced_lib>
> <forced_lib>_collections</forced_lib>
> <forced_lib>_functools</forced_lib>
> <forced_lib>_threading</forced_lib>
> <forced_lib>math</forced_lib>
> <forced_lib>time</forced_lib>
> </xml> 
> 18:48:28.548 DEBUG Fabio python path is : /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/ 
> 18:48:28.549 DEBUG Fabio python path added 
> 18:48:28.550 DEBUG Class paths: 
> 18:48:28.551 DEBUG 	/usr/java/packages/lib/amd64 
> 18:48:28.551 DEBUG 	/usr/lib64 
> 18:48:28.551 DEBUG 	/lib64 
> 18:48:28.551 DEBUG 	/lib 
> 18:48:28.551 DEBUG 	/usr/lib 
> 18:48:28.553 DEBUG Extra plugins: [org.dawnsci.io, de.desy.file.loader] 
> 18:48:28.707 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.boofcv_1.0.0.v20160314-1243/jars/org.boofcv.ip_0.18.0.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.boofcv_1.0.0.v20160314-1243/jars/org.boofcv.sfm_0.18.0.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.boofcv_1.0.0.v20160314-1243/jars/org.boofcv.geo_0.18.0.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.boofcv_1.0.0.v20160314-1243/jars/org.boofcv.feature_0.18.0.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/slf4j.api_1.7.18.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/javax.vecmath_1.5.2.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.gda.common_1.2.0.v20160314-1417.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.apache.commons.math3_3.6.0.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis_1.3.0.v20160422-1025/jars/it.tidalwave.imageio.raw-1.6.1.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis_1.3.0.v20160422-1025/jars/jai_imageio.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/com.springsource.org.apache.commons.collections_3.2.1.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/com.thoughtworks.xstream_1.2.1.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/de.desy.file.loader_1.0.0.v20160316-1244.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.spectroscopy.rcp_1.2.0.v20160315-1153.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.org.apache.xmlrpc.client_3.1.3.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.swt.gtk.linux.x86_64_3.104.2.v20160212-1350.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.polling_1.3.0.v20160224-1134.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.jama_1.0.3.jar  
> 18:48:28.708 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.osgi_1.3.0.v20160314-1239.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.equinox.common_3.7.0.v20150402-1709.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/log4j.over.slf4j_1.7.18.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/ch.qos.logback.classic_1.1.6.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.org.apache.xmlrpc.server_3.1.3.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.processing_1.0.0.v20160421-0804.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.org.apache.xmlrpc.common_3.1.3.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.spectroscopy_1.2.0.v20160314-1233.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.xmlrpc_1.0.0.v20160314-1239.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/com.springsource.javax.media.jai.core_1.1.3.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.nexus_1.0.0.v20160401-1044.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.plotclient_1.0.0.v20160427-1158.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.analysis.tree_1.0.0.v20160315-1356.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.plotting.api_1.2.0.v20160314-1455.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.spectroscopy.ws.rcp_1.2.0.v20160314-1234.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/com.springsource.javax.media.jai.codec_1.1.3.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.CBFlib_1.2.0.v20160407-0856/jars/cbflib-0.9.0.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.apache.commons.codec_1.6.0.v201305230611.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.org.apache.ws.commons.util_1.0.2.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.persistence_1.2.0.v20160427-0826.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.plotserver_1.0.0.v20160314-1239.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.apache.commons.lang_2.6.0.jar  
> 18:48:28.709 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.diffraction.powder_1.0.0.v20160316-1228.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.rcp.contributions_1.3.0.v20160104-1629.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.hdf5.model_1.0.0.v20160401-1044.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/ch.qos.logback.core_1.1.6.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.processing.actor_1.0.0.v20160218-1130.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.swt_3.104.2.v20160212-1350.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.io_1.2.0.v20160311-1218.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.org.jscience4_4.3.1.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.diffraction.powder.rcp_1.0.0.v20160322-1501.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.rcp_1.3.0.v20160322-1458.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.analysis.dataset_1.0.0.v20160417-1601/jars/JTransforms-3.0.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis.peakfinding_1.0.0.v20160314-1239.jar  
> 18:48:28.710 DEBUG Adding jar file to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.analysis.api_1.0.0.v20160314-1455.jar  
> 18:48:28.712 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.boofcv_1.0.0.v20160314-1243 
> 18:48:28.712 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis_1.3.0.v20160422-1025 
> 18:48:28.712 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/ncsa.hdf_2.9.0.v20160408-1007 
> 18:48:28.713 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.hdf5.editor_1.2.0.v20160401-1044 
> 18:48:28.713 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.ddogleg_0.6.0.SNAPSHOT 
> 18:48:28.713 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.plotting.examples_1.0.0.v20160304-1219 
> 18:48:28.713 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.CBFlib_1.2.0.v20160407-0856 
> 18:48:28.714 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.python_1.3.0 
> 18:48:28.714 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.hdf5_1.3.0.v20160407-0957 
> 18:48:28.714 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.analysis.dataset_1.0.0.v20160417-1601 
> 18:48:28.714 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.boofcv_1.0.0.v20160314-1243 
> 18:48:28.714 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis_1.3.0.v20160422-1025 
> 18:48:28.714 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/ncsa.hdf_2.9.0.v20160408-1007 
> 18:48:28.714 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.hdf5.editor_1.2.0.v20160401-1044 
> 18:48:28.714 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.ddogleg_0.6.0.SNAPSHOT 
> 18:48:28.715 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.plotting.examples_1.0.0.v20160304-1219 
> 18:48:28.715 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.CBFlib_1.2.0.v20160407-0856 
> 18:48:28.715 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.python_1.3.0 
> 18:48:28.715 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.hdf5_1.3.0.v20160407-0957 
> 18:48:28.715 DEBUG Adding directory to jython path: /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.analysis.dataset_1.0.0.v20160417-1601 
> 18:48:28.717 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.dawnsci.boofcv_1.0.0.v20160314-1243 
> 18:48:28.717 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.analysis_1.3.0.v20160422-1025 
> 18:48:28.717 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/ncsa.hdf_2.9.0.v20160408-1007 
> 18:48:28.717 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.hdf5.editor_1.2.0.v20160401-1044 
> 18:48:28.718 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.ddogleg_0.6.0.SNAPSHOT 
> 18:48:28.718 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.plotting.examples_1.0.0.v20160304-1219 
> 18:48:28.719 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.CBFlib_1.2.0.v20160407-0856 
> 18:48:28.719 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/uk.ac.diamond.scisoft.python_1.3.0 
> 18:48:28.719 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.hdf5_1.3.0.v20160407-0957 
> 18:48:28.719 DEBUG Found plugin directory /home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/plugins/org.eclipse.dawnsci.analysis.dataset_1.0.0.v20160417-1601 
> 18:48:28.720 DEBUG Setting LD_LIBRARY_PATH for dynamic libraries 
> 18:48:28.720 DEBUG 	/home/reichelt/Programme/DawnDiamond-2.0.0.v20160428-1048-linux64/lib 
> 18:48:28.733 DEBUG Finalising the Jython interpreter manager 
> 18:48:28.738 DEBUG Jython interpreter already exists with exact settings 
> 18:48:28.738 DEBUG Finished the Jython interpreter setup 

Are the errors with the rectangle caused by 18:48:09.650 ERROR Could not create directory /dls/tmp/reichelt , or may there something other be wrong?

Best regards,
DaGeRe

**Comment by PeterC-DLS** [comment]
Hi there,

No, this may be a known problem caused by GTK3 (and/or Ubuntu's desktop). Can you try setting an environment variable in the same shell where you will run dawn?
```
$ export SWT_GTK3=0
$ dawn
```

An alternative is to edit the dawn.ini file and insert the following lines:
```
--launcher.GTK_version
2
```
before the `--launch.appendVmargs` line.

**Comment by DaGeRe** [comment]
Thanks for the quick reply. The first solution with setting the environment variable solved the problem and things looked nearly like in the example.

The second alternative did not change anything. I did it exactly the way you wrote it and without the linebreak, so it looked like this:

> openFile
> --launcher.GTK_version 2
> --launcher.appendVmargs

I am running on Ubuntu 16.04. Is it necessary to clear the workspace or something different, before I start with a new dawn.ini?

**Comment by PeterC-DLS** [comment]
Hmm, not sure, you could try the `-clean` option.

The file editing option should work according to a Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/java-common/+bug/1552764

**Comment by DaGeRe** [comment]
Thanks for the advice, with:

> -startup
> plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
> --launcher.library
> plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417
> -showLocation
> --launcher.defaultAction
> openFile
> -clean
> --launcher.GTK_version 
> 2
> --launcher.appendVmargs
> -vmargs
> -Xms256m
> -Xmx1024m
> -Dosgi.requiredJavaVersion=1.7.0
> -Dcom.isencia.require.file.source=true
> -Dorg.dawb.editor.h5.use.default=false
> -Dosgi.locking=none
> -Dorg.dawnsci.passerelle.do.not.break.osgi=true

it works for me.

**Comment by PeterC-DLS** [comment]
For what it is worth, you do not want the ``-clean`` option in there all the time.
